config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations

  get "/cv", to: "cv#index"
  get "/about", to: "about#index"
  root "letter#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/cv.rb
class Cv < ApplicationRecord
  def self.header
    OpenStruct.new(JSON.parse(File.read("public/cv.json"))).header
  end

  def self.skills
    OpenStruct.new(JSON.parse(File.read("public/cv.json"))).skills
  end

  def self.work_experience
    OpenStruct.new(JSON.parse(File.read("public/cv.json"))).workexperience
  end

  def self.education
    OpenStruct.new(JSON.parse(File.read("public/cv.json"))).education
  end
end

app/models/letter.rb
class Letter < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_current_user, if: :user_signed_in?

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  private

  def set_current_user
    Current.user = current_user
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email])
  end
end

app/controllers/cv_controller.rb
class CvController < ApplicationController
  def index
    @header = Cv.header
    @skills = Cv.skills
    @work_experience= Cv.work_experience
    @education= Cv.education
  end
end

app/controllers/letter_controller.rb
class LetterController < ApplicationController
  before_action :authenticate_user!

  def index
    @content = Letter.get_content(current_user)
  end
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<section>
  <h1 class="text-xl pb-2">About</h1>
  <hr />

  <div class="flex flex-col md:flex-row md:justify-between">
    <article class="md:w-2/3 mt-2 mb-8 space-y-2">
      <p>
        This application is built using Ruby in rails 7, using the alpha 2 release, and Ruby version 3.0.2.
        The gem Devise is used for authentication, with some tinkering (issue <a href="https://github.com/heartcombo/devise/pull/5397" target="_blank" class="text-dark hover:underline">#5397)</a>.
      </p>
      <p>
        TailwindCSS is used for the CSS, the main reason being that I work with it daily. Once I "got"/learned the API, I have never been more productive when working with design implementation.
      </p>
      <p>
        JavaScript and CSS is bundled using the new <a href="https://github.com/rails/jsbundling-rails" target="_blank" class="hover:underline text-dark">jsbundling-rails</a> and <a href="https://github.com/rails/cssbundling-rails" target="_blank" class="hover:underline text-dark">cssbundling-rails</a> gems.
      </p>
      <p>
        The application is deployed using a webhook when pushed to the main branch of the <a href="https://github.com/johanhanses/cv.johanhanses.com" target="_blank" class="hover:underline text-dark">repo</a> through <a href="https://www.hatchbox.io/" target="_blank" class="text-dark hover:underline">Hatchbox.io</a> and runs on a <a href="https://www.digitalocean.com/" target="_blank" class="text-dark hover:underline">Digital ocean</a> droplet.
      </p>
    </article>
  </div>
</section>

app/views/cv/index.html.erb
<section>
  <div>
    <h1 class="text-xl pb-2"><%= @header["name"] %></h1>
    <hr />

    <div class="flex flex-col md:flex-row md:justify-between mt-2 mb-8">
      <div class="w-full md:w-4/6">
        <div class="flex">
          <p class="md:w-2/6">Address:</p>
          <p class="md:w-4/6 pl-4"><%= @header["address"] %></p>
        </div>
        <div class="flex">
          <p class="md:w-2/6">Mobile number:</p>
          <p class="md:w-4/6 pl-4">
            <a href="tel:<%= @header["phone"] %>" class="text-dark hover:underline">
              <%= @header["phone"] %>
            </a>
          </p>
        </div>
        <div class="flex">
          <p class="md:w-2/6">Email:</p>
          <p class="md:w-4/6 pl-4">
            <a href="mailto:<%= @header["email"] %>" class="text-dark hover:underline">
              <%= @header["email"] %>
            </a>
          </p>
        </div>
        <div class="flex">
          <p class="md:w-2/6">Date of birth:</p>
          <p class="md:w-4/6 pl-4"><%= @header["dateofbirth"] %></p>
        </div>
        <div class="flex">
          <p class="md:w-2/6">Github:</p>
          <p class="md:w-4/6 pl-4">
            <a target="_blank" href="<%= @header["github"] %>" class="text-dark hover:underline">
              <%= @header["github"] %>
            </a>
          </p>
        </div>
        <div class="flex">
          <p class="md:w-2/6">LinkedIn:</p>
          <p class="md:w-4/6 pl-4">
            <a target="_blank" href="<%= @header["linkedin"] %>" class="text-dark hover:underline break-all">
              <%= @header["linkedin"] %>
            </a>
          </p>
        </div>
        <div class="flex">
          <p class="md:w-2/6">Languages:</p>
          <p class="md:w-4/6 pl-4 break-words">
            <%= @header["lang"] %>
          </p>
        </div>
        <div class="flex">
          <p class="md:w-2/6">Drivers license:</p>
          <p class="md:w-4/6 pl-4">
            <%= @header["driverslic"] %>
          </p>
        </div>
      </div>

      <div class="order-first md:order-last mb-6 md:mb-0 w-full md:w-auto">
        <%= image_tag "jag.png", alt: "me", class: "h-auto w-auto mx-auto" %>
      </div>
    </div>
  </div>

  <div>
    <h2 class="text-lg pb-2">Skills</h2>
    <hr />

    <div class="mt-2 mb-8 space-y-1">
      <p><strong>Programming: </strong><%= @skills["programming"] %></p>
      <p><strong>Frontend: </strong><%= @skills["frontend"] %></p>
      <p><strong>Backend: </strong><%= @skills["backend"] %></p>
      <p><strong>Databases: </strong><%= @skills["db"] %></p>
      <p><strong>Tooling: </strong><%= @skills["tools"] %></p>
      <p><strong>Testing: </strong><%= @skills["test"] %></p>
      <p><strong>Server: </strong><%= @skills["server"] %></p>
      <p><strong>Other: </strong><%= @skills["other"] %></p>
    </div>
  </div>

  <div class="work">
    <h2 class="text-lg pb-2">Work experience</h2>
    <hr />

    <% @work_experience.each do |work| %>
      <div class="mt-3 mb-8">
        <table>
          <tr>
            <td style="min-width: 110px; vertical-align:top;">
              <%= work["date"] %>
            </td>
            <td class="pl-4">
              <strong><%= work["employee"] %></strong>
            </td>
          </tr>
          <tr>
            <td></td>
            <td class="pl-4">
              <i><%= work["position"] %></i>
            </td>
          </tr>
          <tr>
            <td></td>
            <td class="pl-4"><%= work["description"] %></td>
          </tr>
        </table>
      </div>
    <% end %>
  </div>

  <div>
    <h2 class="text-lg pb-2">Education</h2>
    <hr />

    <% @education.each do |edu| %>
      <div class="mt-3 mb-8">
        <table>
          <tr>
            <td style="min-width: 110px; vertical-align:top;" >
              <%= edu["date"] %>
            </td>
            <td class="pl-4">
              <strong><%= edu["education"] %></strong>
            </td>
          </tr>
          <tr>
            <td></td>
            <td class="pl-4"><%= edu["school"] %></td>
          </tr>
          <tr>
            <td></td>
            <td class="pl-4"><%= edu["points"] %></td>
          </tr>
          <tr class="bottom">
            <td></td>
            <td class="pl-4"><%= edu["description"] %></td>
          </tr>
        </table>
      </div>
    </div>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <title>CV - Johan Hanses</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,300;0,400;0,600;0,700;1,300;1,400;1,600;1,700&display=swap" rel="stylesheet">

    <%= favicon_link_tag "solaire.ico" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="flex flex-col lg:flex-row min-h-screen h-full font-ibm">
  <% if user_signed_in? %>
    <%= render partial: "shared/navbar" %>

    <main class="pt-12 lg:w-3/4 px-6 lg:px-12 text-base md:text-lg">
      <%= yield %>
    </main>
  <% else %>
    <main class="w-full pt-12 flex flex-col items-center">
      <%= yield %>

      <p class="text-yellow-500"><%= notice %></p>
      <p class="text-red-500"><%= alert %></p>
    </main>
  <% end %>
  </body>
</html>

app/views/letter/index.html.erb
<section>
    <h1 class="text-xl pb-2">Johan Hanses</h1>
    <hr />

    <div class="flex flex-col md:flex-row md:justify-between">
        <article class="md:w-2/3">
          <div class="mt-2 mb-8">
            <h2 class="text-lg mb-6">Web developer, passionate about MVC, REST and dynamic scripting languages</h2>

            <div class="pr-4 space-y-3">
              <%= @content %>
            </div>
          </div>
        </article>

        <aside class="md:w-1/3 mt-2 order-first md:order-last mb-6 md:mb-0 w-full md:w-auto">
          <%= image_tag "kallslatten.jpg", alt: "me", class: "h-auto w-auto mx-auto" %>
        </aside>
    </div>
</section>

app/views/shared/_desktop_menu.html.erb
<aside class="hidden lg:flex w-1/4 bg-dark text-white pt-12 flex-col items-end px-12">
  <div class="uppercase text-3xl mb-24 text-right">
    <p>Hello <%= Current.user.username ? Current.user.username : '' %>!</p>
  </div>

  <nav class="uppercase text-xl space-y-6 text-right">
    <%= link_to 'Cover letter', root_path, class: class_names("hover:underline block", { active: current_page?(root_path) }) %>
    <%= link_to 'CV', cv_path, class: class_names("hover:underline block", { active: current_page?(cv_path) }) %>
    <%= link_to 'About', about_path, class: class_names("hover:underline block", { active: current_page?(about_path) }) %>
  </nav>

  <address class="mt-8 text-right">
    <a href="mailto:johanhanses@gmail.com" class="inline-block not-italic border border-white p-2 px-6 rounded-full hover:bg-white hover:text-dark transition-colors duration-300">johanhanses@gmail.com</a>
    <a href="tel:+46735506928" class="mt-4 inline-block not-italic border border-white p-2 px-6 rounded-full hover:bg-white hover:text-dark transition-colors duration-300">073-550 69 28</a>
  </address>

  <nav class="text-sm text-right">
    <%= button_to 'Log out', destroy_user_session_path, method: :delete,  class: " uppercase hover:underline block mt-24" %>
  </nav>
</aside>

app/views/shared/_mobile_header.html.erb
<header class="lg:hidden w-full h-16 bg-dark">
  <div
    data-controller="menu"
    class="w-full h-full text-white flex items-center justify-between px-6 relative"
  >

    <div>
      <%= link_to root_path, class: "uppercase text-xl" do %>
        Hello <%= Current.user.username ? Current.user.username : '' %>!
      <% end %>
    </div>

    <div data-action="click->menu#toggle">
      <button
        data-menu-target="burger"
        class="focus:outline-none focus:ring-2 focus:ring-blue-500 mt-2"
        id="options-menu"
        aria-haspopup="true"
        aria-expanded="true"
        aria-label="open menu"
      >
        <svg viewBox="0 0 100 80" class="text-white fill-current h-8 w-8">
          <rect width="100" height="12" rx="0"></rect>
          <rect y="30" width="100" height="12" rx="0"></rect>
          <rect y="60" width="100" height="12" rx="0"></rect>
        </svg>
      </button>

      <button
        data-menu-target="cross"
        class="focus:outline-none focus:ring-2 focus:ring-blue-500 mt-2 hidden"
        id="options-menu"
        aria-haspopup="true"
        aria-expanded="true"
        aria-label="close menu"
      >

        <svg viewBox="0 0 94.926 94.926" class="fill-current text-white h-6 w-6">
          <g>
            <path
              d="M55.931,47.463L94.306,9.09c0.826-0.827,0.826-2.167,0-2.994L88.833,0.62C88.436,0.224,87.896,0,87.335,0
              c-0.562,0-1.101,0.224-1.498,0.62L47.463,38.994L9.089,0.62c-0.795-0.795-2.202-0.794-2.995,0L0.622,6.096
              c-0.827,0.827-0.827,2.167,0,2.994l38.374,38.373L0.622,85.836c-0.827,0.827-0.827,2.167,0,2.994l5.473,5.476
              c0.397,0.396,0.936,0.62,1.498,0.62s1.1-0.224,1.497-0.62l38.374-38.374l38.374,38.374c0.397,0.396,0.937,0.62,1.498,0.62
              s1.101-0.224,1.498-0.62l5.473-5.476c0.826-0.827,0.826-2.167,0-2.994L55.931,47.463z"
            />
          </g>
        </svg>
      </button>
    </div>

    <div
      data-menu-target="menu"
      class="hidden absolute right-0 top-16 left-0 bg-dark shadow-lg origin-top transition-all duration-300"
    >
      <div class="p-6 text-left space-y-3 text-xl uppercase" role="menu">
        <%= link_to 'Cover letter', root_path, class: class_names("hover:underline block", { active: current_page?(root_path) }) %>

        <%= link_to 'CV', cv_path, class: class_names("hover:underline block", { active: current_page?(cv_path) }) %>

        <%= link_to 'About', about_path, class: class_names("hover:underline block", { active: current_page?(about_path) }) %>

        <%= button_to 'Log out', destroy_user_session_path, method: :delete,  class: "uppercase hover:underline inline-block" %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_navbar.html.erb
<%= render partial: "shared/mobile_header" %>

<%= render partial: "shared/desktop_menu" %>